# Generated by Django 5.1.4 on 2025-01-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='pictures/profilepic.jpg', upload_to='profile_pics'),
        ),
    ]
